### ISSUE TITLE
Random error related to private messages

### ISSUE THREAD

**Issue by arj03** [ssb-ngi-pointer/ssb-db2#115]
Encrypted

    ✔ no err
/home/runner/work/ssb-db2/ssb-db2/test/ebt.js:77
        t.equal(msg.value.content, content)
                    ^

TypeError: Cannot read property 'value' of undefined
    at /home/runner/work/ssb-db2/ssb-db2/test/ebt.js:77:21
    at /home/runner/work/ssb-db2/ssb-db2/indexes/ebt.js:72:18
    at /home/runner/work/ssb-db2/ssb-db2/indexes/ebt.js:50:23
    at /home/runner/work/ssb-db2/ssb-db2/node_modules/levelup/lib/levelup.js:192:14
    at /home/runner/work/ssb-db2/ssb-db2/node_modules/encoding-down/index.js:75:21

**Comment by arj03** [comment]
From [here](https://github.com/ssb-ngi-pointer/ssb-db2/runs/1649107981)
