### ISSUE TITLE
"stackless error" when replicating

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#151]
I believe this might be related to createHistoryStream compat layer, since that's something I enabled recently (and I only now got this error because things finished indexing, and after that it starts ssb-conn, which allows users to call createHistoryStream on me)

Notice "error replicating with" mentions an SSB ID which is not me.

```
01-28 19:23:31.180  5363  5409 E NODEJS-MOBILE: Error replicating with @WKgGmvyGuwab30ZsNzuuJnLb35nBYt16AsSXJ2Mngfs=.ed25519:
01-28 19:23:31.180  5363  5409 E NODEJS-MOBILE:    
01-28 19:28:44.214  5363  5409 E NODEJS-MOBILE: Error: stackless error
01-28 19:28:44.214  5363  5409 E NODEJS-MOBILE:     at module.exports (/data/data/se.manyver/files/nodejs-project/index.js:68543:19)
01-28 19:28:44.214  5363  5409 E NODEJS-MOBILE:     at abort (/data/data/se.manyver/files/nodejs-project/index.js:23268:45)
01-28 19:28:44.214  5363  5409 E NODEJS-MOBILE:     at Object.cb (/data/data/se.manyver/files/nodejs-project/index.js:23275:24)
01-28 19:28:44.214  5363  5409 E NODEJS-MOBILE:     at drain (/data/data/se.manyver/files/nodejs-project/index.js:42059:23)
01-28 19:28:44.214  5363  5409 E NODEJS-MOBILE:     at /data/data/se.manyver/files/nodejs-project/index.js:42076:18
01-28 19:28:44.214  5363  5409 E NODEJS-MOBILE:     at /data/data/se.manyver/files/nodejs-project/index.js:42033:7
01-28 19:28:44.214  5363  5409 E NODEJS-MOBILE:     at PacketStreamSubstream.weird.read (/data/data/se.manyver/files/nodejs-project/index.js:42564:7)
01-28 19:28:44.214  5363  5409 E NODEJS-MOBILE:     at PacketStream._onstream (/data/data/se.manyver/files/nodejs-project/index.js:63815:12)
01-28 19:28:44.214  5363  5409 E NODEJS-MOBILE:     at PacketStream.write (/data/data/se.manyver/files/nodejs-project/index.js:63750:41)
01-28 19:28:44.214  5363  5409 E NODEJS-MOBILE:     at /data/data/se.manyver/files/nodejs-project/index.js:42587:15
```

**Comment by staltz** [comment]
Oh, I think this was something totally else. Ignore (for now. maybe I reopen it)
