### ISSUE TITLE
Maybe some problems with EBT getAtSequence

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#152]
Similar diagnosis as #151 

```
01-29 00:15:27.417 11039 11072 E NODEJS-MOBILE: TypeError: Cannot read property 'get' of undefined
01-29 00:15:27.417 11039 11072 E NODEJS-MOBILE:     at EventEmitter.db.getAtSequence (/data/data/se.manyver/files/nodejs-project/index.js:42837:14)
01-29 00:15:27.417 11039 11072 E NODEJS-MOBILE:     at EventEmitter.hooked [as getAtSequence] (/data/data/se.manyver/files/nodejs-project/index.js:69292:15)
01-29 00:15:27.417 11039 11072 E NODEJS-MOBILE:     at Object.getAt (/data/data/se.manyver/files/nodejs-project/index.js:19203:12)
01-29 00:15:27.417 11039 11072 E NODEJS-MOBILE:     at Object.update (/data/data/se.manyver/files/nodejs-project/index.js:45069:18)
01-29 00:15:27.417 11039 11072 E NODEJS-MOBILE:     at EBTStream.write (/data/data/se.manyver/files/nodejs-project/index.js:64300:13)
01-29 00:15:27.417 11039 11072 E NODEJS-MOBILE:     at next (/data/data/se.manyver/files/nodejs-project/index.js:41936:21)
01-29 00:15:27.417 11039 11072 E NODEJS-MOBILE:     at PacketStreamSubstream.weird.read (/data/data/se.manyver/files/nodejs-project/index.js:42564:7)
01-29 00:15:27.417 11039 11072 E NODEJS-MOBILE:     at PacketStream._onstream (/data/data/se.manyver/files/nodejs-project/index.js:63819:12)
01-29 00:15:27.417 11039 11072 E NODEJS-MOBILE:     at PacketStream.write (/data/data/se.manyver/files/nodejs-project/index.js:63750:41)
01-29 00:15:27.417 11039 11072 E NODEJS-MOBILE:     at /data/data/se.manyver/files/nodejs-project/index.js:42587:15
```

Relevant lines of code:

```js
  db.getAtSequence = function (seqid, cb) {
    // will NOT expose private plaintext
    db.clock.get(isString(seqid) ? seqid.split(':') : seqid, function (err, value) {
      if (err) cb(err)
      else cb(null, u.originalData(value))
    })
  }
```

**Comment by arj03** [comment]
Did you enable EBT using db2 already? The code you listed there is from db1. And looks like the clock index is gone?

**Comment by staltz** [comment]
Aahh ok I think I know what to do

**Comment by staltz** [comment]
Yeah this was just my fault in not installing correctly
