### ISSUE TITLE
Occasional levelup error `ReadError: Database is not open`

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#35]
I get this error randomly when running `DEBUG=* npm test`:

```
  refuses to db2.add() while old log exists

  secret-stack Adding transport net +316ms
  secret-stack Adding transform shs +1ms
  jitdb indexes path /tmp/ssb-db2-migrate/db2/indexes +20ms
  secret-stack net plugin creating transport host=undefined port=NaN scope=device,local,public +331ms
  secret-stack creating server net shs host=undefined port=NaN scope=device,local,public +14ms
  secret-stack net plugin creating transport host=undefined port=NaN scope=device,local,public +1ms
  secret-stack net plugin creating transport host=undefined port=NaN scope=undefined +0ms
  multiserver:net Listening on false:49915 +19ms
  async-flumelog opened file, since: 10447 +46ms
  async-flumelog getting offset 0 from disc +1ms
  ssb:db2:migrate new log has 11 msgs, will continue migrating +315ms
  ssb:db2:migrate reading old log +1ms
  ssb:db2:base got index status: { version: 1, seq: 7607, processed: 11 } +0ms
    ✔ should be truthy
    ✔ should be falsy
    ✔ error message is about the old log
  ssb:db2:migrate done migrating 0 msgs from old log +14ms
  async-flumelog getting offset 7607 from cache +22ms
  ssb:db2:base index scan time: 1ms, items: 12 +15ms

/home/staltz/ssb-db2/indexes/plugin.js:43
          if (err) throw err
                   ^
ReadError: Database is not open
    at maybeError (/home/staltz/ssb-db2/node_modules/.pnpm/levelup@4.4.0/node_modules/levelup/lib/levelup.js:339:32)
    at LevelUP.put (/home/staltz/ssb-db2/node_modules/.pnpm/levelup@4.4.0/node_modules/levelup/lib/levelup.js:211:7)
    at writeBatch (/home/staltz/ssb-db2/indexes/plugin.js:38:13)
    at Object.end (/home/staltz/ssb-db2/indexes/plugin.js:69:11)
    at Stream.abort (/home/staltz/ssb-db2/node_modules/.pnpm/async-flumelog@1.0.8/node_modules/async-flumelog/stream.js:150:15)
    at blocks.getBlock (/home/staltz/ssb-db2/node_modules/.pnpm/async-flumelog@1.0.8/node_modules/async-flumelog/stream.js:134:12)
    at Object.getBlock (/home/staltz/ssb-db2/node_modules/.pnpm/async-flumelog@1.0.8/node_modules/async-flumelog/index.js:95:7)
    at Stream._resume (/home/staltz/ssb-db2/node_modules/.pnpm/async-flumelog@1.0.8/node_modules/async-flumelog/stream.js:123:15)
    at Stream._next (/home/staltz/ssb-db2/node_modules/.pnpm/looper@4.0.0/node_modules/looper/index.js:11:9)
    at Stream.resume (/home/staltz/ssb-db2/node_modules/.pnpm/async-flumelog@1.0.8/node_modules/async-flumelog/stream.js:140:8)
```

**Comment by arj03** [comment]
Yeah strange, I just got it in the CI now as well.

**Comment by staltz** [comment]
I get this somewhat frequently, so I'll keep a counter here how many times I've gotten this error.

**COUNTER: 3** (to be updated)

**Comment by arj03** [comment]
When this counter reaches **666** the rapture begins. 


In all seriousness, I can now reliably reproduce this problem so gonna fix it I hope :-)

**Comment by arj03** [comment]
The dragon has been defeated!

**Comment by staltz** [comment]
That was quick!!

**Comment by staltz** [comment]
Should this be closed?

**Comment by arj03** [comment]
I'll close it, please reopen if you get it again

**Comment by staltz** [comment]
Welcome back!

```
  live votesFor

    ✔ no err
    ✔ no err
    ✔ should be strictly equal
    ✔ no err
    ✔ should be strictly equal

/home/staltz/oss/manyverse/ssb-db2/indexes/plugin.js:39
          if (err) throw err
                   ^
ReadError: Database is not open
    at maybeError (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/levelup@4.4.0/node_modules/levelup/lib/levelup.js:339:32)
    at LevelUP.put (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/levelup@4.4.0/node_modules/levelup/lib/levelup.js:211:7)
    at writeBatch (/home/staltz/oss/manyverse/ssb-db2/indexes/plugin.js:34:13)
    at Object.onData (/home/staltz/oss/manyverse/ssb-db2/indexes/plugin.js:59:42)
    at indexesRun.forEach (/home/staltz/oss/manyverse/ssb-db2/db.js:274:54)
    at Array.forEach (<anonymous>)
    at write (/home/staltz/oss/manyverse/ssb-db2/db.js:274:37)
    at Object.o.write (/home/staltz/oss/manyverse/ssb-db2/log.js:43:29)
    at Stream._writeToSink (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/async-flumelog@1.0.10/node_modules/async-flumelog/stream.js:57:32)
    at Stream._handleBlock (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/async-flumelog@1.0.10/node_modules/async-flumelog/stream.js:91:12)
```

**Comment by staltz** [comment]
Putting this dragon to sleep. Hope it doesn't awake again
