### ISSUE TITLE
(Sometimes) errors when testing getAllLatest

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-db2#68]
In the `master` branch as of now, this happens probabilistically. Might be related to the `stateLoaded` changes I made, since I haven't seen this one before.

```
  get all latest

    ✔ no err
    ✔ authors

    ✖ should be strictly equal
    ---------------------------
      operator: equal
      expected: '%vXvTSDTQ1DhKvrLGyb1gSrJ4I0XYCgFQKf9xtVWcrik=.sha256'
      actual:   '%Gav5Mr9yyb1B7nsbYQb6OwSnH4c5ddjy+eKpf/4LhGI=.sha256'
      at: db.getAllLatest (/home/staltz/oss/manyverse/ssb-db2/test/base-index.js:134:11)
      stack: |-
  Error: should be strictly equal
  at Test.assert [as _assert] (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/tape@5.0.1/node_modules/tape/lib/test.js:260:54)
  at Test.bound [as _assert] (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/tape@5.0.1/node_modules/tape/lib/test.js:84:32)
  at Test.strictEqual (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/tape@5.0.1/node_modules/tape/lib/test.js:424:10)
  at Test.bound [as equal] (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/tape@5.0.1/node_modules/tape/lib/test.js:84:32)
  at db.getAllLatest (/home/staltz/oss/manyverse/ssb-db2/test/base-index.js:134:11)
  at pull.collect (/home/staltz/oss/manyverse/ssb-db2/indexes/base.js:108:9)
  at /home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/pull-stream@3.6.14/node_modules/pull-stream/sinks/reduce.js:10:5
  at /home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/pull-stream@3.6.14/node_modules/pull-stream/sinks/drain.js:20:24
  at drain (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/stream-to-pull-stream@1.7.3/node_modules/stream-to-pull-stream/index.js:126:18)
  at ReadStream.<anonymous> (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/stream-to-pull-stream@1.7.3/node_modules/stream-to-pull-stream/index.js:143:5)


    ✖ should be strictly equal
    ---------------------------
      operator: equal
      expected: 8
      actual:   9
      at: db.getAllLatest (/home/staltz/oss/manyverse/ssb-db2/test/base-index.js:135:11)
      stack: |-
  Error: should be strictly equal
  at Test.assert [as _assert] (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/tape@5.0.1/node_modules/tape/lib/test.js:260:54)
  at Test.bound [as _assert] (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/tape@5.0.1/node_modules/tape/lib/test.js:84:32)
  at Test.strictEqual (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/tape@5.0.1/node_modules/tape/lib/test.js:424:10)
  at Test.bound [as equal] (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/tape@5.0.1/node_modules/tape/lib/test.js:84:32)
  at db.getAllLatest (/home/staltz/oss/manyverse/ssb-db2/test/base-index.js:135:11)
  at pull.collect (/home/staltz/oss/manyverse/ssb-db2/indexes/base.js:108:9)
  at /home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/pull-stream@3.6.14/node_modules/pull-stream/sinks/reduce.js:10:5
  at /home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/pull-stream@3.6.14/node_modules/pull-stream/sinks/drain.js:20:24
  at drain (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/stream-to-pull-stream@1.7.3/node_modules/stream-to-pull-stream/index.js:126:18)
  at ReadStream.<anonymous> (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/stream-to-pull-stream@1.7.3/node_modules/stream-to-pull-stream/index.js:143:5)


    ✖ should be strictly equal
    ---------------------------
      operator: equal
      expected: 1607517717512
      actual:   1607517717773
      at: db.getAllLatest (/home/staltz/oss/manyverse/ssb-db2/test/base-index.js:136:11)
      stack: |-
  Error: should be strictly equal
  at Test.assert [as _assert] (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/tape@5.0.1/node_modules/tape/lib/test.js:260:54)
  at Test.bound [as _assert] (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/tape@5.0.1/node_modules/tape/lib/test.js:84:32)
  at Test.strictEqual (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/tape@5.0.1/node_modules/tape/lib/test.js:424:10)
  at Test.bound [as equal] (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/tape@5.0.1/node_modules/tape/lib/test.js:84:32)
  at db.getAllLatest (/home/staltz/oss/manyverse/ssb-db2/test/base-index.js:136:11)
  at pull.collect (/home/staltz/oss/manyverse/ssb-db2/indexes/base.js:108:9)
  at /home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/pull-stream@3.6.14/node_modules/pull-stream/sinks/reduce.js:10:5
  at /home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/pull-stream@3.6.14/node_modules/pull-stream/sinks/drain.js:20:24
  at drain (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/stream-to-pull-stream@1.7.3/node_modules/stream-to-pull-stream/index.js:126:18)
  at ReadStream.<anonymous> (/home/staltz/oss/manyverse/ssb-db2/node_modules/.pnpm/stream-to-pull-stream@1.7.3/node_modules/stream-to-pull-stream/index.js:143:5)


  encrypted

    ✔ no err
    ✔ should be strictly equal
```

**Comment by arj03** [comment]
Should be fixed now
